### ISSUE TITLE
Change OAuth redirect URL

### ISSUE THREAD

**Issue by sdunster** [NSWSESMembers/availability-web#3]
I've deployed it via S3 fronted by CloudFront here: https://web.callout.nsws.es

Can you please change the OAuth redirect URL (on the identity server) for the current OAuth app id/key/token to go to:
https://web.callout.nsws.es/redirect

Then also update it in code. Let me know when done and I'll push new code so the OAuth flow begins to work.

If you wish to continue testing on localhost you might need to create a new OAuth app id/key/token. The OAuth server might also support allowing multiple redirect URLs so you could investigate that as well.

**Comment by aschick82** [comment]
Thanks Sam. I can use Identity Server Dev for my own development and will change the redirect url with Identity Test.

**Comment by aschick82** [comment]
Will let you know

**Comment by aschick82** [comment]
Sam, all good now. The Redirect Url is now updated to the one you mentioned. Also I added a enviromnent check to the global config.

**Comment by aschick82** [comment]
I close this issue now as it's done.
